project:
  type: 
    website
    
execute:
  freeze:
    auto

website:
  title: "quarto-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - gdp.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



